# Generated by Django 4.2.5 on 2023-10-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_evento_usuario_eventoregistrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='week',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend')], max_length=20),
        ),
    ]
