# Generated by Django 4.2.5 on 2023-10-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_registrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='detalles',
            field=models.CharField(max_length=500),
        ),
    ]
