# Generated by Django 4.2.5 on 2023-10-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_registrado_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='detalles',
            field=models.TextField(),
        ),
    ]
