# Generated by Django 4.2.5 on 2023-10-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_alter_registrado_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='week',
        ),
    ]
